### ISSUE TITLE
程式碼與論文設計不一致

### ISSUE THREAD

**Issue by paul0728** [HKUDS/KGRec#10]
作者您好,
在trace完程式碼以後,有些問題想要請教您:
1.KGRec.py combine two mask,而論文沒有此設計
2.為何在class KGRec 的forward 函式當中, 
item_attn_mean_1[item_attn_mean_1 == 0.] = 1.
item_attn_mean_2[item_attn_mean_2 == 0.] = 1.
不太理解為何要把score 最低的item設為最高?
3.計算contrastive loss時,依照公式17,分母應該會產生4倍的between_sim(j分別以v,v',v''帶入公式)而不是程式碼所寫之兩倍的between_sim
4.
公式17,
應該是把所有item下之loss相加而非程式碼之取平均
5.
公式14,
對應程式碼應該使用_bi_norm_lap(adj),而程式碼卻使用_si_norm_lap(adj)是為何?

**Comment by yuh-yang** [comment]
感谢你对我们工作细致的关注，你提到的4和5确实是我们写作时疏忽的地方，产生了与code的一些细微偏差，请以code实现为准。对于1，2，3:

1. 这个只是一个优化模型训练的minor trick，通过在mask中掺入一些随机因素来加快模型收敛、避免局部最优，因为并不是一个主要的设计，所以没有involve到论文写作中
2. 这个过程中1.0其实是最小值，因为rational_score*N_neighbor的值总是大于1
3. between_sim是正样本之间的score，j分別以v,v',v''帶入公式只会得到两个正样本对

**Comment by paul0728** [comment]
2.最小值不能直接使用原本的0嗎?
3.依照公式
j=v 代入會產生2個正樣本對
j=v'代入會產生1個正樣本對
j=v''代入會產生1個正樣本對
所以應該共4個正樣本對才對吧?

謝謝

**Comment by yuh-yang** [comment]
2. 这里的自然最小值是1而非0，因为rational_score*N_neighbor的值总是大于1。其实改成0也可以，毕竟一般来说不会影响topk
3. 随机负样本v', v''是没有各自的ego正样本的，而且分母中分别代入v,v',v''一共也是4个term，即两对正负样本

**Comment by paul0728** [comment]
![image](https://github.com/HKUDS/KGRec/assets/44644609/1a63aa87-a5bf-44fa-ac32-190cb8a73b6a)
3.根據以上公式,分母項
當j=v代入 : 產生兩倍exp(𝑠 (z𝑣 , z𝑣 )/𝜏[兩倍between_sim]
當j=v'代入 : 產生exp(𝑠 (z𝑣 , z𝑣 )/𝜏) + exp(𝑠 (z𝑣' , z𝑣 )/𝜏)[一倍between_sim]
當j=v'代入 : 產生exp(𝑠 (z𝑣 , z𝑣 )/𝜏) + exp(𝑠 (z𝑣'' , z𝑣 )/𝜏)[一倍between_sim]

故一共應為四倍between_sim 吧?
如果按照程式碼的算法的話公式在分母的地方應改為,
𝑗 ∈ {𝑣 ′ ,𝑣 ′′}

**Comment by yuh-yang** [comment]
get你的意思了，这里公式应该是将\sum符号放置在第二项之前，感谢你的意见，我们会在预印版中进行修正

**Comment by paul0728** [comment]
了解

**Comment by yuh-yang** [comment]
closed due to inactiveness
