### ISSUE TITLE
数据集具体内容

### ISSUE THREAD

**Issue by congyaya** [HKUDS/KGRec#12]
数据集中展示的是item和entity的id，请问该如何找到entity对应的name呢? 我希望可以进一步了解kg包含的具体内容，但是，例如，last-fm的kg抽取自freebase,但是基于kg里的org_id，我还没有找到id映射到name的方法。

**Comment by yuh-yang** [comment]
你好，可以尝试在wikidata中按照"freebase_id"这一项进行query，也可以直接下载整个freebase镜像来查找entity name

**Comment by yuh-yang** [comment]
closed due to inactiveness

**Comment by Genius-pig** [comment]
wikidata大部分找不到，我目前就找到一个，m.0181lj。
https://query.wikidata.org/querybuilder/?uselang=en
