### ISSUE TITLE
processing dataset 

### ISSUE THREAD

**Issue by Pursuerwener** [HKUDS/KGRec#13]
Could you explain how your dataset is processed？Thanks

**Comment by yuh-yang** [comment]
Except for MIND, the datasets are inherited from KGIN and KGAT.

For MIND, I perform user-based sampling and 5-core filtering based on the raw data, and referring to the KG provided in https://github.com/WHUIR/KOPRA to construct the KG

**Comment by yuh-yang** [comment]
closed due to inactiveness
