### ISSUE TITLE
 ran code on the ml-10m dataset

### ISSUE THREAD

**Issue by NanGongNingYi** [HKUDS/KGRec#15]
Hello, author. I ran your code on the ml-10m dataset and found that the experiment did not work well, do you know why?
![image](https://github.com/HKUDS/KGRec/assets/61775768/c6a7cd88-08e3-4dc5-99ea-b0906623e5d0)

**Comment by Genius-pig** [comment]
请问一下你数据是咋处理的

**Comment by yuh-yang** [comment]
Hi, sorry for delayed response.

Would you share your HP settings, including in which ranges did you tune the HPs?

We can check it together on how to optimize KGRec on more datasets! :)

**Comment by yuh-yang** [comment]
Temporarily closed due to inactiveness.
