### ISSUE TITLE
model problem

### ISSUE THREAD

**Issue by Pursuerwener** [HKUDS/KGRec#3]
Thank you very much for sharing
i run the code python run_kgrec.py --dataset last-fm to process the dataset
When I ran it(python run_kgrec.py --dataset last-fm) the second time to train
i get this error

NameError: name 'test_user_set' is not defined

**Comment by Pursuerwener** [comment]
![20230905091956(1)](https://github.com/HKUDS/KGRec/assets/103307623/c1534bd2-e4ba-4d24-9250-f5c288d5946e)
after i run the code python run_kgrec.py --dataset ailibaba-fashion 
i run the code again
i get this running report
And then I got the above error.Unable to obtain results
Requesting Your Help

**Comment by wangte123** [comment]
> ![20230905091956(1)](https://user-images.githubusercontent.com/103307623/265560579-c1534bd2-e4ba-4d24-9250-f5c288d5946e.png) 在我的运行代码 python run_kgrec.py --dataset ailibaba-fashion 之后， 我再次运行代码， 我得到了这个运行报告 ，然后我得到了这个错误。 无法获取结果 NameError: name 'test_user_set' is not Defined 请求您的帮助

我也出现了这个问题，请问您解决了吗

**Comment by wangte123** [comment]
> Hi,
> 
> Can you post the error stack track so that I can better help?
为什么会出现上述情况呀，为什么train_cf_triples：那个进度条不动，和楼上情况一样

**Comment by yuh-yang** [comment]
看起来只是因为打印了std值，截断了一次tqdm progress bar的打印而已，运行时有error吗？

**Comment by yuh-yang** [comment]
@Pursuerwener 

it's strange since `test_user_set ` should be globalized at line 117 `global train_user_set, test_user_set` .

Would you provide full script for `evaluate_kgsr.py`?

**Comment by Pursuerwener** [comment]
Thanks for your reply
yes，I noticed your code `global train_user_set, test_user_set` as soon as I started reproducing it.
This error also exists in the `evaluate.py` when i run the `run_kgin.py`
Fortunately,the running of KGCL is no problem
[code.zip](https://github.com/HKUDS/KGRec/files/12583736/code.zip)

**Comment by yuh-yang** [comment]
That's because KGCL uses a class-based evaluator. I guess the problem lies in multiprocessing on Windows. Plz try any of the potential solutions:

1. use Linux
2. use KGCL's class-based evaluator for KGIN and KGRec
3. stop using multiprocessing for test_one_user

**Comment by Pursuerwener** [comment]
i use your second method
i get this error
`Traceback (most recent call last):
  File "run_kgin.py", line 126, in <module>
    ret = Evaluator.test(model, user_dict, n_params)
TypeError: test() missing 1 required positional argument: 'n_params'
`
running the `run_kgrec.py`is the same as above
but i checked the `evaluator.py`,it' no problem 
i think that the problem is processing on Windows

**Comment by yuh-yang** [comment]
You have to modify your codes to pass `n_params` to Evaluator.test()
