### ISSUE TITLE
Does batch size affect the results?

### ISSUE THREAD

**Issue by paul0728** [HKUDS/KGRec#4]
Hello, does the batch size affect the result? I found that using the default batch size:1024 takes a long time to run, so I want to make the batch size a little bit bigger to speed up, thank you!

**Comment by yuh-yang** [comment]
Hi,

It should have minor affect if you adjust it to 512 or 256

**Comment by paul0728** [comment]
感謝您的回應,想再請問幾個問題:
1.如果將batch size設成4096 ,8192,會不會有影響?
2.kgrec/kgin/kgcl 在readme中預設的參數是否是最佳參數?
3.使用kgrec 按照原本設置,一個epoch要跑30分鐘,請問這樣是正常的嗎?(我在3090上執行)
4.是否能提供有效率的調整參數的方法?

**Comment by yuh-yang** [comment]
Hi,

1. I actually didn't try other batch size settings, but from my experiences, a value under 4096 should be generally fine in terms of performance affect.

2. Yes. They are.

3. My device is 3090 too, and one epoch here takes around 800 secs for iFashion and Last-FM, and 700 secs for MIND. 30 mins seem abnormal. Would you check your GPU load during running?

4. From my experiences, performances are less sensitive in regard to mask_size and drop_ratio than tau. You can tune tau first if limited time provided. You can see from A.1 that as long as you don't assign an edge value to mask_size and drop_ratio, the performances would be fine with mask_size at 256 or 512 and drop_ratio at 0.5 or 0.6.

**Comment by paul0728** [comment]
Thank you very much!
