### ISSUE TITLE
Rationale Masking Mechanism

### ISSUE THREAD

**Issue by paul0728** [HKUDS/KGRec#6]
您好,論文裡有不解之處想請教您:
![Screenshot from 2023-09-12 00-43-20](https://github.com/HKUDS/KGRec/assets/44644609/1f53fe2b-fdf8-4348-9011-af9f2cce4444)

這裡是取top 𝑘-highest rational scores 之triplet集合:Mk
但是為何下面寫說'we remove the edges M𝑘 with **low rationale scores**...'
謝謝

**Comment by yuh-yang** [comment]
sorry这里是一个typo，应该是remove edges with highest rationale scores

感谢指出，我们会及时在preprint中更正

**Comment by paul0728** [comment]
了解
