### ISSUE TITLE
baseline性能问题

### ISSUE THREAD

**Issue by wangxin211** [HKUDS/KGRec#7]
请问一下论文里复现SGL时，采用的是哪个代码以及参数设置。

**Comment by yuh-yang** [comment]
https://github.com/Coder-Yu/SELFRec

n_layer:2  
lambda:[0.1, 0.2, 0.5]
droprate:[0.2, 0.3, 0.4, 0.5]  
temp: [0.1, 0.2]

**Comment by wangxin211** [comment]
在SELFRec框架下，SGL 参数设置-n_layer 2 -lambda 0.1 -droprate 0.1 -augtype 1 -temp 0.2
 在Alibaba-ifashion数据集上可以跑到0.12的结果。为社么droprate没有选择0.1呢。

**Comment by yuh-yang** [comment]
你好，当时凭经验从0.2开始搜参，也对比了SELFRec、RecBole和我们自己的SSLRec的SGL的结果，选取了指标上最高的SELFRec版本。我去试一下0.1的rate
