### ISSUE TITLE
加速模型訓練

### ISSUE THREAD

**Issue by paul0728** [HKUDS/KGRec#8]
作者您好,
我照您原本設置執行run_kgrec.py
以下為各個dataset下一個epoch之執行時間
last-fm : 15min
![Screenshot from 2023-09-13 18-37-47](https://github.com/HKUDS/KGRec/assets/44644609/108fe0e6-6f79-45eb-a338-414d3f388c76)

mind-f : 2h26min 
![Screenshot from 2023-09-13 18-36-13](https://github.com/HKUDS/KGRec/assets/44644609/8252ff57-0c37-4628-9b6b-d9a737453490)

alibaba-fashion : 32min
![Screenshot from 2023-09-13 18-43-07](https://github.com/HKUDS/KGRec/assets/44644609/ea856aed-ad68-41ed-94c4-73440820965c)

執行環境 : 
system : Ubuntu 20.04.5 LTS
CPU : Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
GPU : NVIDIA GeForce RTX 3090

檢查GPU和CPU皆正常運作
請問該如何使執行時間如您在之前issue所述 : **800 secs for iFashion and Last-FM, and 700 secs for MIND**
謝謝

**Comment by yuh-yang** [comment]
你好，我的CPU是[Intel® Xeon® Silver 4314](https://www.intel.com/content/www/us/en/products/sku/215269/intel-xeon-silver-4314-processor-24m-cache-2-40-ghz/specifications.html)

感觉你这边瓶颈可能在CPU，可以尝试用time package找一下最耗cpu时间的操作，然后再看看怎么优化。有可能的是：
1. 训练负采样
2. masking
3. contrastive data augmentation

**Comment by llj-dp** [comment]
你好，你跑完last-fm数据集用了多少时间呀  按照1024的batch-size
